services:
  postgres:
    image: postgres:15-alpine
    container_name: glust-db
    environment:
      POSTGRES_USER: glust
      POSTGRES_PASSWORD: glust
      POSTGRES_DB: glust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
